name: pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Format
        run: test -z "$(gofmt -l .)"

      - name: Lint
        uses: golangci/golangci-lint-action@v7

      - name: Build
        run: go build -o cuebernetes main.go

      - name: Test
        run: go test -v ./...
